panel-util: switch to generic header for --disable-x11
panel-util.c:31:10: fatal error: 'gdk/gdkx.h' file not found
 #include <gdk/gdkx.h>
          ^~~~~~~~~~~~